export const ROUTES = {
    HOME: '/',
    BROWSE: '/browse',
    SIGNUP: '/signup',
    SIGNUP_PASSWORD: '/signup/password',
    SIGNIN: '/signin',
    // "/continue",
    LOGIN: '/login',
    REGISTRATION: '/registration',
    REGFORM: '/signup/regform',
    // REGFORM: '/regform',
    PLANFORM: '/signup/planform',
    // PLANFORM: '/planform',
    PAYMENT_OPTION: '/signup/payment-option',
    // PAYMENT_OPTION: '/payment-option',
    CREATE_PROFILES: '/signup/create-profiles',
    // CREATE_PROFILES: '/create-profiles',
};
